export const SOLVE_EXPERT_SYSTEM = "SOLVE_EXPERT_SYSTEM";
export const SOLVE_EXPERT_SYSTEM_SUCCESS = "SOLVE_EXPERT_SYSTEM_SUCCESS";
export const CLEAR_EXPERT_SYSTEM_RESULT = "CLEAR_EXPERT_SYSTEM_RESULT";